services:
  flask:
    image: dubithal/weather-app:latest
    container_name: flask
    ports:
      - "5000:5000"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - FLASK_ENV=development
    networks:
      - app-network

  nginx:
    image: dubithal/nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ec2-user/dubi-proj/app/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - flask
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
