global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['flask:5000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    deploy:
      resources:
        limits:
          memory: 300M
